//
//  UIColor+DMSAdditions.swift
//
//  Generated by Zeplin on 11/8/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {
	class var dmsPaleTeal: UIColor {
		return UIColor(red: 155.0 / 255.0, green: 215.0 / 255.0, blue: 200.0 / 255.0, alpha: 1.0)
	}
    class var dmsPaleTealTwo: UIColor {
        return UIColor(red: 129.0 / 255.0, green: 189.0 / 255.0, blue: 174.0 / 255.0, alpha: 1.0)
    }

	class var dmsLightNavy: UIColor {
		return UIColor(red: 14.0 / 255.0, green: 60.0 / 255.0, blue: 82.0 / 255.0, alpha: 1.0)
	}
    
    class var dmsOffBlue: UIColor {
        return UIColor(red: 78.0 / 255.0, green: 157.0 / 255.0, blue: 167.0 / 255.0, alpha: 1.0)
    }

    class var dmsCloudyBlue: UIColor {
        return UIColor(red: 209.0 / 255.0, green: 213.0 / 255.0, blue: 225.0 / 255.0, alpha: 1.0)
    }
    
    class var dmsCloudyBlueTwo: UIColor {
        return UIColor(red: 187.0 / 255.0, green: 190.0 / 255.0, blue: 206.0 / 255.0, alpha: 1.0)
    }

    class var dmsBlueyGrey: UIColor {
        return UIColor(red: 160.0 / 255.0, green: 164.0 / 255.0, blue: 186.0 / 255.0, alpha: 1.0)
    }
    
    class var dmsMetallicBlue: UIColor {
        return UIColor(red: 62.0 / 255.0, green: 99.0 / 255.0, blue: 116.0 / 255.0, alpha: 1.0)
    }
    
    class var dmsMetallicBlue75: UIColor {
        return UIColor(red: 62.0 / 255.0, green: 99.0 / 255.0, blue: 116.0 / 255.0, alpha: 0.75)
    }
    
    class var dmsViridian: UIColor {
        return UIColor(red: 34.0 / 255.0, green: 133.0 / 255.0, blue: 146.0 / 255.0, alpha: 1.0)
    }
    
    class var dmsPineGreen: UIColor {
        return UIColor(red: 11.0 / 255.0, green: 48.0 / 255.0, blue: 65.0 / 255.0, alpha: 1.0)
    }
    
    class var dmsCloudyBlue60: UIColor {
        return UIColor(red: 209.0 / 255.0, green: 213.0 / 255.0, blue: 225.0 / 255.0, alpha: 0.6)
    }
    
    class var dmsTomato: UIColor {
        return UIColor(red: 239.0 / 255.0, green: 62.0 / 255.0, blue: 49.0 / 255.0, alpha: 1.0)
    }

    class var dmsTomatoTwo: UIColor {
        return UIColor(red: 236.0 / 255.0, green: 76.0 / 255.0, blue: 72.0 / 255.0, alpha: 1.0)
    }

    class var dmsBlueGreen: UIColor {
        return UIColor(red: 27.0 / 255.0, green: 106.0 / 255.0, blue: 116.0 / 255.0, alpha: 1.0)
    }
    
    class var dmsPaleGrey: UIColor {
        return UIColor(red: 235.0 / 255.0, green: 237.0 / 255.0, blue: 245.0 / 255.0, alpha: 1.0)
    }
    class var dmsPaleGreyTwo: UIColor {
        return UIColor(red: 243.0 / 255.0, green: 244.0 / 255.0, blue: 247.0 / 255.0, alpha: 1.0)
    }

    class var dmsPaleGreyHighlighted: UIColor {
        return UIColor(red: 235.0 / 255.0, green: 237.0 / 255.0, blue: 245.0 / 255.0, alpha: 0.6)
    }
    
    class var dmsHighlightedWhite: UIColor {
        return UIColor(red: 235.0 / 255.0, green: 235.0 / 255.0, blue: 235.0 / 255.0, alpha: 1.0)
    }
    
    class var dmsOkBlue: UIColor {
        return UIColor(red: 155.0 / 255.0, green: 215.0 / 255.0, blue: 200.0 / 255.0, alpha: 1.0)
    }

    class var dmsOrange: UIColor {
        return UIColor(red: 252.0 / 255.0, green: 192.0 / 255.0, blue: 79.0 / 255.0, alpha: 1.0)
    }
    
    class var dmsSad: UIColor {
        return UIColor(red: 252.0 / 255.0, green: 81.0 / 255.0, blue: 69.0 / 255.0, alpha: 1.0)
    }
    class var dmsMango: UIColor {
        return UIColor(red: 252.0 / 255.0, green: 177.0 / 255.0, blue: 35.0 / 255.0, alpha: 1.0)
    }
    class var dmsDullTeal: UIColor {
        return UIColor(red: 104.0 / 255.0, green: 164.0 / 255.0, blue: 149.0 / 255.0, alpha: 1.0)
    }
    class var dmsPineGreen90: UIColor {
        return UIColor(red: 11.0 / 255.0, green: 48.0 / 255.0, blue: 65.0 / 255.0, alpha: 0.95)
    }

}
